### ISSUE TITLE
You cant inject any Clients.

### ISSUE THREAD

**Issue by KeksNino** [CubeWhyMC/celestial#100]
You cant inject any hack clients like Slinky or Vape and i think no injectable works but ive just tested it with these two.

**Comment by KeksNino** [comment]
it doesnt work with both xrk and hacklc

**Comment by cubewhy** [comment]
change your api and disable celewrap

**Comment by KeksNino** [comment]
to what should i change the api? also the weave loader in celestial launcher seems to be different from the weave loader from original weave manager and does not work and crashes on startup and it opens a window where it says that the weave mods that are installed do not look like weave mods but they are. i fixed it by disabling weave update checker and replacing the loader with the original weave loader
![grafik](https://github.com/user-attachments/assets/357251d7-3252-45c1-bed7-46d2285b8c21)

**Comment by cubewhy** [comment]
Celestial launches LC v2333 by default, this version will override your .lunarclient folder from a newer LC version.
You can change the api to `https://api.lunarclientprod.com` to solve this problem (restart required).

**Comment by KeksNino** [comment]
i still cant inject any clients.
