### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by win2000MEMZ** [CubeWhyMC/celestial#21]
java8还是java17都启动不了
java8用java.exe弹的窗
![屏幕截图 2024-01-30 182146](https://github.com/CubeWhyMC/celestial/assets/110439586/993c4f72-0b78-452e-849d-85031ac8f754)
java17用java.exe弹的窗
![屏幕截图 2024-01-30 182244](https://github.com/CubeWhyMC/celestial/assets/110439586/32292cdd-45f7-4ec8-baad-4294697bfd3d)

**Comment by cubewhy** [comment]
`java -jar celestial.jar` 而不是 `java celestial.jar`
