### ISSUE TITLE
Change LunarQT Cracked Account Nickname

### ISSUE THREAD

**Issue by BrandowLucas** [CubeWhyMC/celestial#22]
Is there a way to change the LunarQT cracked account nickname? I saw that you recently comitted LCQT2 features but not a way to change the cracked nickname, apparently.

Nice software by the way.

**Comment by cubewhy** [comment]
try to add a game param `--username yournickname`

**Comment by BrandowLucas** [comment]
That works. Thanks

Maybe try adding a typing box on the LunarQT settings on the next update for better accessibility and user-friendliness.

**Comment by cubewhy** [comment]
I'll do that
