### ISSUE TITLE
API无法访问https://api.lunarclient.top

### ISSUE THREAD

**Issue by duanygithub** [CubeWhyMC/celestial#27]
2024/2/6 15:18，对"https://api.lunarclient.top/launcher/metadata" 请求返回404导致无法正常启动。curl这个url也返回404
![image](https://github.com/CubeWhyMC/celestial/assets/85821056/673484a6-07e1-4982-b304-9a6f87494ab1)
![image](https://github.com/CubeWhyMC/celestial/assets/85821056/55fae264-1065-4ccb-bf3c-6699c00ac7ab)
版本为Actions的build #260，文件名celestial-2.1-SNAPSHOT-fatjar.jar

**Comment by muskf** [comment]
你好，https://api.lunarclient.top/launcher/metadata的确无法再访问。原因是我们已经迁移了api地址，新的api地址是https://www.lunarclient.top/api
你可以切换到此api地址以正确加载程序。

**Comment by duanygithub** [comment]
你好，我解决了问题，非常感谢你的解答。
