### ISSUE TITLE
Game is crashing (total top of the game.log) if you have a space in your username folder.

### ISSUE THREAD

**Issue by MaciejK2** [CubeWhyMC/celestial#45]
Selfexplanatory, 'C:\Users\...' is not recognized as an internal or external command,
operable program or batch file. (... - username + space + rest of name that it didnt output)

Should be an easy fix i guess, i will try to search for it in src in the meantime.

**Comment by MaciejK2** [comment]
Fixed this in like 20 minutes of trying, in \.cubewhy\lunarcn\launch.bat add " before every C: and at the end of the paths. It works after this.

**Comment by cubewhy** [comment]
please send launch.bat
