### ISSUE TITLE
lunar微软账户无法登录

### ISSUE THREAD

**Issue by nbdexiaoyu** [CubeWhyMC/celestial#77]
将重定向的链接复制到登录框中后lunar显示成功，但Sign in任然存在且无法进入游戏

**Comment by cubewhy** [comment]
不要使用XRK Lunar进行登入

**Comment by nbdexiaoyu** [comment]
hacklc Lunar任然无法登录

**Comment by nbdexiaoyu** [comment]
![image](https://github.com/user-attachments/assets/569ba51c-7730-4bbb-9c3e-2bb238ef9d3d)

**Comment by Ahqzyk** [comment]
Pls help me no work me the Lunar-CN 

![image](https://github.com/user-attachments/assets/1ec655e4-e22b-40d0-ae10-1a16eb3f2f1e)

![image](https://github.com/user-attachments/assets/019072ff-26b6-436b-8988-ed2d14ba30db)

**Comment by nbdexiaoyu** [comment]
give me your game.log

**Comment by nbdexiaoyu** [comment]
Wait CubeWhyMc

**Comment by Ahqzyk** [comment]
Nbdexiaoyu pls help me :(

**Comment by cubewhy** [comment]
> ![image](https://github.com/user-attachments/assets/569ba51c-7730-4bbb-9c3e-2bb238ef9d3d)
> 
> 

换API
https://api.lunarclientprod.com

**Comment by nbdexiaoyu** [comment]
![image](https://github.com/user-attachments/assets/fd67a7d5-9fae-491a-9d8a-648e85fd5462)

**Comment by nbdexiaoyu** [comment]
![image](https://github.com/user-attachments/assets/95d01b61-0c9b-4d08-9c6d-b1196e07de90)

**Comment by nbdexiaoyu** [comment]
额？

**Comment by cubewhy** [comment]
No slash in end of the url
