### ISSUE TITLE
Pls help me no work the LUNAR_CN

### ISSUE THREAD

**Issue by Ahqzyk** [CubeWhyMC/celestial#78]
![image](https://github.com/user-attachments/assets/8b157bf2-c1c1-4f27-a3f8-22844e46809f)
![image](https://github.com/user-attachments/assets/34598bfd-0f19-41d2-9c3e-841828da7511)

**Comment by nbdexiaoyu** [comment]
Pls check if your JAVA is Azul's jdk-17

**Comment by nbdexiaoyu** [comment]
Check game integrity

**Comment by nbdexiaoyu** [comment]
Try to delete c:/users/yourname/.Cubewhy and /.weave

**Comment by nbdexiaoyu** [comment]
Or delete the entire game!

**Comment by nbdexiaoyu** [comment]
That's what I can help you with

**Comment by nbdexiaoyu** [comment]
Pls go to find CubeWhyMc

**Comment by Ahqzyk** [comment]
Ok thanks wait

**Comment by nbdexiaoyu** [comment]
Where are you from？
