### ISSUE TITLE
Lunar changed its API.

### ISSUE THREAD

**Issue by jollyeqweqe** [CubeWhyMC/celestial#96]
Hey I'm from your discord server, I was having some difficulty making celestial open, so I told you what was in my log in the discord server and you stated that Lunar changed its API, which will need to be fixed. I was also told to upload my launcher.log and game.log here so the attachments are down below.

[launcher.log](https://github.com/user-attachments/files/17176662/launcher.log)
[game.log](https://github.com/user-attachments/files/17176664/game.log)

**Comment by cubewhy** [comment]
nothing helpful from the log
Can you click Fetch Json and send the version metadata to me?

**Comment by jollyeqweqe** [comment]
not sure if this is what your looking for but I clicked "Fetch json" and then saved it and got this
[jolly.json](https://github.com/user-attachments/files/17176758/jolly.json)

**Comment by jollyeqweqe** [comment]
I did not mean to close it my bad

**Comment by cubewhy** [comment]
Lunat haven't changed api.
This is a problem with Celestial
PS: I forgot to add ichor args

**Comment by jollyeqweqe** [comment]
> Lunat haven't changed api. This is a problem with Celestial PS: I forgot to add ichor args

so this is something you'll have to fix?

**Comment by cubewhy** [comment]
I have no computer these months :(

**Comment by jollyeqweqe** [comment]
> I have no computer these months :(

that sucks, so it wont be fixed anytime soon?

**Comment by jollyeqweqe** [comment]
> I have no computer these months :(

hey i just want to tell you know btw, that celestial just randomly started working and all the cosmetics and everything is working perfectly
